if(ANDROID_NDK_TOOLCHAIN_INCLUDED)
   include(CMake/android_config.cmake)
elseif (WIN32)
   include(CMake/windows_config.cmake)
   MESSAGE(STATUS "OS detected: Windows")
elseif (EMSCRIPTEN)
   include(CMake/emscripten_config.cmake)
   MESSAGE(STATUS "OS detected: EMSCRIPTEN")
else()
   include(CMake/unix_config.cmake)
   MESSAGE(STATUS "OS detected: Unix")
endif()
